# Generated by Django 5.1.1 on 2024-10-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
